#!/bin/bash
# changeBrightness

msgTag="myBrightness"

brightness="$(brightnessctl g)"

brightnessctl set "$@" > /dev/null

dunstify -a "changeBrightness" -u low -i audio-volume-high -h string:x-dunst-stack-tag:$msgTag \
        -h int:value:"$((brightness*100/255))" "Brightness: $((brightness*100/255))%"
